services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: NDA4ZGU4LThmNmQtNDExMS1hNjk1LTFiNTk1YjVjYzkxMQ==
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 5s
      timeout: 5s
      retries: 10

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx128M"

  db:
    image: postgres:15
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    env_file:
      - ./auth/.env
    container_name: auth
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "5001:8081"
    environment:
      - KAFKA__BOOTSTRAP_SERVERS=kafka:9092
      - ENV=dev
      - CONFIG_PATH=config/dev.yaml

  authorchestrator:
    build:
      context: ./authOrchestrator
      dockerfile: Dockerfile
    env_file:
      - ./authOrchestrator/.env
    container_name: authorchestrator
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "5002:8082"
    environment:
      - KAFKA__BOOTSTRAP_SERVERS=kafka:9092
      - ENV=dev
      - CONFIG_PATH=config/dev.yaml

  content:
    build:
      context: ./content
      dockerfile: Dockerfile
    env_file:
      - ./content/.env
    container_name: content
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "5003:8083"
    environment:
      - KAFKA__BOOTSTRAP_SERVERS=kafka:9092
      - ENV=dev
      - CONFIG_PATH=config/dev.yaml

  mailer:
    build:
      context: ./mailer
      dockerfile: Dockerfile
    env_file:
      - ./mailer/.env
    container_name: mailer
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "5004:8084"
    environment:
      - KAFKA__BOOTSTRAP_SERVERS=kafka:9092
      - ENV=dev
      - CONFIG_PATH=config/dev.yaml

volumes:
  db_data: