env: "local" #local, dev, prod
db_connection_string: "user=postgres.vtcfqwszewtyqpghoiaa password=WHSE5JxPTrYTSjzv host=aws-1-eu-west-1.pooler.supabase.com port=5432 dbname=postgres"
http_server:
  address: "localhost:8083"
  timeout: 4s
  iddle_timeout: 60s